# Generated by Django 4.0.1 on 2022-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_user_user_email_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(max_length=25)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
